### ISSUE TITLE
Zone transfer problem with 9.11.3-20190706

### ISSUE THREAD

**Issue by geschke** [sameersbn/docker-bind#80]
Hello!

I'm running two docker-bind containers for master and slave DNS. The master is still running with 9.11.3-20190315. After a system upgrade I updated the slave to 9.11.3-20190706 and started with the same parameters and persistent storage folder as before. 

A test of zone transfer didn't work, here's the output:

```
Testing transfer of slave zone from ..
.. from : Failed : /usr/bin/dig: couldn't get address for '': not found

```
There is a master server in the "Zone Options", and zone transfer is allowed. 

After a day testing I switched back to  9.11.3-20190315 - and it worked again! 

My run command:

```

docker run --name bind -d --restart=always \
> --env ROOT_PASSWORD=superduperpassword \
> --publish IPADDRESS:53:53/udp --publish IPADDRESS:53:53/tcp --publish IPADDRESS:10000:10000 \
> --volume /srv/docker/bind:/data \
> sameersbn/bind

```

Maybe this is a similar problem as in #74 ?

System:

```
 docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Any help is appreciated! 

Kind regards,
   Ralf

**Comment by mrbatwood** [comment]
My zone transfers aren't working either, and I'm just about to move to vanilla DNS in VMs.  They worked when I first setup the slave servers, to transfer the records that were there then, but haven't happened since -- despite me tuning every parameter I could find to force them more quickly, configure the slaves everywhere, and open up access lists.  I'm using the latest version of everything since i just installed.

It's frustrating that there is an older version of Webmin still installed -- that has the bug with testing the zone transfers.  Still, testing the zone transfers is not as useful as having them just work!  ;^)
